export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: 'user/SET_CURRENT_USER',
  CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
  GOOGLE_SIGNIN_START: 'user/GOOGLE_SIGNIN_START',
  EMAIL_SIGNIN_START: 'user/EMAIL_SIGNIN_START',
  GOOGLE_SIGNUP_START: 'user/GOOGLE_SIGNUP_START',
  EMAIL_SIGNUP_START: 'user/EMAIL_SIGNUP_START',
  SIGNIN_SUCCESS: 'user/SIGNIN_SUCCESS',
  SIGNIN_FAIL: 'user/SIGNIN_FAIL',
  SIGNUP_SUCCESS: 'user/SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'user/SIGNUP_FAIL',
  SIGN_OUT_START: 'user/SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'user/SIGN_OUT_SUCCESS',
  SIGN_OUT_FAIL: 'user/SIGN_OUT_FAIL',
}

